apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # This makes it the default StorageClass
provisioner: ebs.csi.aws.com
parameters:
  type: gp2  # Type of EBS volume, can also use 'gp3' for better performance and cost
reclaimPolicy: Retain  # Specifies that the volume should be retained after PVC deletion
volumeBindingMode: WaitForFirstConsumer  # Ensures the volume is provisioned in the same zone as the pod
